import { VIDEO_BASE } from "./media";

export type Category = "Ads" | "Social" | "Motion" | "Travel" | "More";
export type Ratio = "16:9" | "9:16" | "1:1" | "4:5" | "21:9";

export type Project = {
  id: string;
  title: string;
  category: Category;
  ratio: Ratio;
  year: string;
  video?: string;
  // Optional longer cut used only in the lightbox — for pieces where the
  // grid preview is a short trimmed-down clip (kept light for the mosaic)
  // but the full piece is worth watching once someone clicks in.
  fullVideo?: string;
};

export const CATEGORIES: Category[] = ["Ads", "Social", "Motion", "Travel", "More"];

// Fixed order, most eye-catching first — no shuffling. Re-ordered by hand
// after reviewing actual footage, not just titles.
export const PROJECTS: Project[] = [
  {
    id: "p-kurzgesagt",
    title: "Kurzgesagt Robot",
    category: "Motion",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/kurzgesagt-robot.mp4`,
  },
  {
    id: "p-around-the-moon",
    title: "Around the Moon Animation",
    category: "Motion",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/around-the-moon-animation.mp4`,
  },
  {
    id: "p-ecosystems",
    title: "Ecosystems Animation",
    category: "Motion",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/ecosystems-animation.mp4`,
  },
  {
    id: "p-fish-swimming",
    title: "Fish Swimming",
    category: "Motion",
    ratio: "4:5",
    year: "2026",
    video: `${VIDEO_BASE}/fish-swimming.mp4`,
  },
  {
    id: "p-proximity",
    title: "Proximity Animation",
    category: "Motion",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/proximity-animation.mp4`,
  },
  {
    id: "p-mosaic",
    title: "Mosaic Animation",
    category: "Motion",
    ratio: "1:1",
    year: "2026",
    video: `${VIDEO_BASE}/mosaic-animation.mp4`,
  },
  {
    id: "p-mascot",
    title: "Walking Penguin Animation",
    category: "Motion",
    ratio: "1:1",
    year: "2026",
    video: `${VIDEO_BASE}/mascot-walk.mp4`,
  },
  {
    id: "p-doctor",
    title: "Doctor Animation",
    category: "Motion",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/doctor-animation.mp4`,
  },
  {
    id: "p-dolomites-2",
    title: "Dolomites Pt.2",
    category: "Travel",
    ratio: "21:9",
    year: "2025",
    video: `${VIDEO_BASE}/dolomites-pt-2.mp4`,
  },
  {
    id: "p-dolomites-1",
    title: "Dolomites Pt.1",
    category: "Travel",
    ratio: "21:9",
    year: "2025",
    video: `${VIDEO_BASE}/dolomites-pt-1.mp4`,
  },
  {
    id: "p-tamasopo",
    title: "Tamasopo",
    category: "Travel",
    ratio: "21:9",
    year: "2025",
    video: `${VIDEO_BASE}/tamasopo-2025.mp4`,
  },
  {
    id: "p-likhubula",
    title: "Likhubula River",
    category: "More",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/likhubula-river.mp4`,
    fullVideo: `${VIDEO_BASE}/likhubula-river-full.mp4`,
  },
  {
    id: "p-sparkling",
    title: "Sparkling Energy SIZZLE",
    category: "Ads",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/sparkling-energy-sizzle.mp4`,
  },
  {
    id: "p-huddles-babysitter",
    title: "Huddle's Babysitter",
    category: "Motion",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/huddles-babysitter.mp4`,
  },
  {
    id: "p-big-interview",
    title: "Big Interview",
    category: "Motion",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/big-interview.mp4`,
  },
  {
    id: "p-click",
    title: "Click Animation",
    category: "Motion",
    ratio: "1:1",
    year: "2026",
    video: `${VIDEO_BASE}/click-animation.mp4`,
  },
  {
    id: "p-motion-art",
    title: "Motion Art Animation",
    category: "Motion",
    ratio: "1:1",
    year: "2026",
    video: `${VIDEO_BASE}/motion-art-animation.mp4`,
  },
  {
    id: "p-standard-process",
    title: "Standard Process Vet Formulas",
    category: "Motion",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/standard-process-vet-formulas.mp4`,
  },
  {
    id: "p-lemonlight",
    title: "LemonLight Reels",
    category: "Social",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/lemonlight-reels.mp4`,
  },
  {
    id: "p-casa-brisa",
    title: "Casa Brisa",
    category: "Social",
    ratio: "9:16",
    year: "2023",
    video: `${VIDEO_BASE}/casa-brisa.mp4`,
  },
  {
    id: "p-zoho",
    title: "Zoho City",
    category: "Ads",
    ratio: "16:9",
    year: "2023",
    video: `${VIDEO_BASE}/zoho-city.mp4`,
  },
  {
    id: "p-nascar",
    title: "Ticketpurchase NASCAR",
    category: "Ads",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/ticketpurchase-nascar.mp4`,
  },
  {
    id: "p-oregon-press",
    title: "Oregon Video Press",
    category: "Ads",
    ratio: "16:9",
    year: "2023",
    video: `${VIDEO_BASE}/oregon-video-press.mp4`,
  },
  {
    id: "p-contractor-exam",
    title: "Goald Cost Schools Contractor Exam",
    category: "Social",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/goald-cost-schools-contractor-exam.mp4`,
  },
  {
    id: "p-trailer-autoservicio",
    title: "Trailer Autoservicio",
    category: "More",
    ratio: "16:9",
    year: "2026",
    video: `${VIDEO_BASE}/trailer-autoservicio.mp4`,
  },
  {
    id: "p-kristi-borglum",
    title: "Kristi Borglum Moneta Blog",
    category: "More",
    ratio: "4:5",
    year: "2026",
    video: `${VIDEO_BASE}/kristi-borglum-moneta-blog.mp4`,
  },
  {
    id: "p-casa-roka-overview",
    title: "Casa Roka Overview",
    category: "Social",
    ratio: "9:16",
    year: "2022",
    video: `${VIDEO_BASE}/casa-roka-overview.mp4`,
  },
  {
    id: "p-casa-roka-bedrooms",
    title: "Casa Roka Bedrooms",
    category: "Social",
    ratio: "9:16",
    year: "2022",
    video: `${VIDEO_BASE}/casa-roka-bedrooms.mp4`,
  },
  {
    id: "p-casa-teresa-restaurant",
    title: "Casa Teresa Restaurant",
    category: "Social",
    ratio: "9:16",
    year: "2022",
    video: `${VIDEO_BASE}/casa-teresa-restaurant.mp4`,
  },
  {
    id: "p-casa-teresa-bar",
    title: "Casa Teresa Bar",
    category: "Social",
    ratio: "9:16",
    year: "2022",
    video: `${VIDEO_BASE}/casa-teresa-bar.mp4`,
  },
  {
    id: "p-kings-sweatshirt",
    title: "Kings Sweatshirt",
    category: "Ads",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/kings-sweatshirt.mp4`,
  },
  {
    id: "p-armstrong-ai",
    title: "Armstrong Lee & Baker AI Reel",
    category: "Ads",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/armstrong-lee-baker-ai-reel.mp4`,
  },
  {
    id: "p-armstrong-offshore",
    title: "Armstrong Lee & Baker Offshore",
    category: "Ads",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/armstrong-lee-baker-offshore.mp4`,
  },
  {
    id: "p-slicktext",
    title: "SlickText Youtube Short",
    category: "Social",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/slicktext-youtube-short.mp4`,
  },
  {
    id: "p-motive-knee-pain",
    title: "Motive Knee Pain",
    category: "Social",
    ratio: "4:5",
    year: "2026",
    video: `${VIDEO_BASE}/motive-knee-pain.mp4`,
  },
  {
    id: "p-box-office",
    title: "BoxOfficeTicketSales",
    category: "Ads",
    ratio: "9:16",
    year: "2026",
    video: `${VIDEO_BASE}/box-office-ticket-sales.mp4`,
  },
];
